<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/main/Arifmetik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(6).reshape(2, 3)
arr2 = np.arange(6, 12).reshape(2, 3)

In [3]:
arr1  # 1-massiv

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
arr2  # 2-massiv

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
arr1 * arr2  # ikki massiv ko'paytmasi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [6]:
arr1 / arr2  # ikki massiv bo'linmasi

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [7]:
arr1 + arr2  # ikki massiv yig'indisi

array([[ 6,  8, 10],
       [12, 14, 16]])

In [8]:
arr1 - arr2  # ikki massiv ayirmasi

array([[-6, -6, -6],
       [-6, -6, -6]])

In [9]:
arr1**2  # square

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [10]:
arr2**(1/2)  # sqrt

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])