<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/main/Array_o'qlarini_almashtirish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [9]:
a = np.arange (6).reshape (3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
a.T

array([[0, 2, 4],
       [1, 3, 5]])

In [12]:
a.swapaxes(1, 0)

array([[0, 2, 4],
       [1, 3, 5]])

In [13]:
np.dot (a, a.T)  # Tranposening ishlatilinishiga bir misol


array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])