<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/main/Boolean_indexlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [14]:
names = np.array (["Otabek", "Muzaffar", "E'zoza", "Sunnat", "Alisher", "Feruza"])
names

array(['Otabek', 'Muzaffar', "E'zoza", 'Sunnat', 'Alisher', 'Feruza'],
      dtype='<U8')

In [15]:
data = np.random.randn (6, 3)
data

array([[ 1.7063056 ,  1.60160628,  0.70915027],
       [ 0.97163676, -0.73407266, -1.32651401],
       [ 1.29641705, -0.88992591, -0.95061986],
       [-1.53420362, -0.97080281,  0.48052864],
       [ 0.20226052,  0.72200158,  0.33973984],
       [-0.34634261,  0.03228203,  0.68366173]])

In [17]:
names == "Muzaffar"

array([False,  True, False, False, False, False])

In [18]:
data [names == "Muzaffar"]

array([[ 0.97163676, -0.73407266, -1.32651401]])

In [19]:
data [names != "Otabek"]

array([[ 0.97163676, -0.73407266, -1.32651401],
       [ 1.29641705, -0.88992591, -0.95061986],
       [-1.53420362, -0.97080281,  0.48052864],
       [ 0.20226052,  0.72200158,  0.33973984],
       [-0.34634261,  0.03228203,  0.68366173]])

In [21]:
data [ data < 0]

array([-0.73407266, -1.32651401, -0.88992591, -0.95061986, -1.53420362,
       -0.97080281, -0.34634261])

In [24]:
data [data > 0] = 0
data

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        , -0.73407266, -1.32651401],
       [ 0.        , -0.88992591, -0.95061986],
       [-1.53420362, -0.97080281,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-0.34634261,  0.        ,  0.        ]])

In [27]:
arr = (names == "Otabek") | (names == "Muzaffar")
arr

array([ True,  True, False, False, False, False])

In [28]:
data [names != "Otabek", 2:]

array([[-1.32651401],
       [-0.95061986],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ]])