<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/main/Indexlash_va_kesish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   # numpy kutubxonasini chaqirdik

In [2]:
arr = np.arange(10,100,10)  # 10 dan 100 gacha 10ta birlikm tashab chiqardik
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
print (arr [-1])  # n-raqamli elementini chiqardik
print (arr [0])
print (arr [6])

90
10
70


In [7]:
print (arr [:])
print (arr [3:5])

[10 20 30 40 50 60 70 80 90]
[40 50]


In [9]:
cut_arr = arr [2:6]  # kesib olinishi : orqali bo'ladi
cut_arr [:] = 50
cut_arr

array([50, 50, 50, 50])

In [10]:
arr

array([10, 20, 50, 50, 50, 50, 70, 80, 90])

In [11]:
cut_arr1 = arr [2:6].copy()  # tog'ridan tog'ri kesib olsak asosiy massivga
                               # ta'sir qilishi mumkin shuning uchun .copy() metodidan foydalanamiz
cut_arr1 [:] = 24
cut_arr1

array([24, 24, 24, 24])

In [12]:
arr

array([10, 20, 50, 50, 50, 50, 70, 80, 90])

In [15]:
arr2d = np.array ([[1, 2, 3],   # 2 o'lchamli massiv
                  [4, 5, 6],
                  [7, 8 ,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
print (arr2d [1, 2])
print (arr2d [:2, 2:])

6
[[3]
 [6]]


In [19]:
arr3d = np.array([[[ 0,  1,  2],  # 3 o'lchamli massiv
                   [ 3,  4,  5],
                   [ 6,  7,  8]],

                  [[ 9, 10, 11],
                   [12, 13, 14],
                   [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [21]:
arr3d [1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [22]:
arr3d [1][2, 2]  # birinchi massivning o'zining kelish tartibi keyin esa keladigan elementini aniqlaymiz

17

In [23]:
arr3d [2][1, 2]

23

In [27]:
print (arr3d [0])
print (arr3d [2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
