<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/main/List_vs_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data1 = [23, 15, 12, -0.26, 14.226, -95] # list
arr1 = np.array (data1) # array (massivli jadval)
print (arr1)
arr1

[ 23.     15.     12.     -0.26   14.226 -95.   ]


array([ 23.   ,  15.   ,  12.   ,  -0.26 ,  14.226, -95.   ])

In [ ]:
data2 = (25, 62, 36, -95, -0.36, -15.2) # tupple
arr2 = np.array(data2) # array (massivli jadval)
arr2

array([ 25.  ,  62.  ,  36.  , -95.  ,  -0.36, -15.2 ])

In [ ]:
arr1.ndim  # massiv o'lchami

1

In [ ]:
arr2.ndim

1

In [ ]:
data3 = [[1, 2, 3], [4, 5, 6]] # list ichidagi ma'lumot
arr3 = np.array(data3)
print(arr3)
arr3.ndim

[[1 2 3]
 [4 5 6]]


2

In [ ]:
data4 = [[1, 2, 3], [4, 5, 6],[7, 8, 9]] # list
arr4 = np.array(data4) # array
print (arr4)
arr4.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [ ]:
arr3.shape # qator va ustunlar (raw and column) r/c


(2, 3)

In [ ]:
arr4.shape

(3, 3)

In [ ]:
arr3.size # massiv ichidagi elementlar sonini aniqlaydi

6

In [ ]:
arr4.size

9