<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/main/Ma'lumotlar_turi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
arr1 = np.array ([1, 2, 3, 4], dtype = np.float64)  # float64 ma'lumot turiga tegishli arr1 o'zgaruvchiarr2
arr1

array([1., 2., 3., 4.])

In [8]:
arr2 = np.array ([5, 6, 7, 8, 9], dtype = np.int32)
arr2

array([5, 6, 7, 8, 9], dtype=int32)

In [9]:
arr3 = np.array ([10, 12.5, 65.3, -85], dtype = np.int32)
arr3

array([ 10,  12,  65, -85], dtype=int32)

In [14]:
arr2.dtype

dtype('int32')

In [16]:
float_arr = arr3.astype (np.int32)
float_arr

array([ 10,  12,  65, -85], dtype=int32)

In [19]:
int_data = np.array ([56.2, 25.9, 69.01])
float_data = int_data.astype (np.int32)
float_data

array([56, 25, 69], dtype=int32)