<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/main/Mantiqiy_shart_operatori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
xarr = [15, 66, 45, 89, 58, 20]
yarr = [26, 54, 78, 56, 24, 30]
qiymat = [True, False, True, False, False, True]

In [3]:
result = np.where (qiymat, xarr, yarr)
result

array([15, 54, 45, 56, 24, 20])

In [5]:
arr = np.random.randn (4, 4)
arr

array([[ 1.11186225,  0.33505892,  0.5206232 , -1.44076606],
       [ 1.33915677, -0.84651097,  0.12369152,  0.40901428],
       [-0.44282398, -0.17805371, -0.98055576, -0.71414161],
       [ 1.48357605,  0.16474781,  1.44486207,  1.08701994]])

In [8]:
result1 = np.where (arr > 0, 56, -56)   # agar taxminiy massiv musbat bo'lsa 56, manfiy bo'lsa -56 ni ko'rsat
result1

array([[ 56,  56,  56, -56],
       [ 56, -56,  56,  56],
       [-56, -56, -56, -56],
       [ 56,  56,  56,  56]])