<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/main/Matematik_va_statistik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr = np.random.randn(5, 5)
arr

array([[-0.48274814, -0.16458034, -0.35118096, -0.23518093, -0.28556424],
       [-0.53780919, -0.7577302 ,  0.56304952,  1.07203261, -0.24005578],
       [ 2.97461715,  0.52348617, -0.22350607, -0.62213846,  0.81965424],
       [-0.34201292, -0.36264743,  0.66697955,  0.33645294,  0.75300631],
       [-0.67643076,  0.40410617,  1.15007298,  0.2753492 ,  1.3460658 ]])

In [4]:
np.sum(arr)  # umumiy massiv yig'indisi

5.603287229030629

In [5]:
np.sum(arr, axis = 1)  # axis=1 bu Column yig'indisi mos ravishda

array([-1.51925461,  0.09948696,  3.47211303,  1.05177845,  2.49916339])

In [7]:
np.sum(arr, axis = 0) # axis=0 bu Row yig'indisi mos ravishda

array([ 0.93561614, -0.35736563,  1.80541502,  0.82651536,  2.39310634])

In [9]:
arr1 = np.arange (15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.mean (arr1)  # 0 ~ 14 gacha bo'lgan sonlar o'rta arifmetigi

7.0

In [11]:
arr

array([[-0.48274814, -0.16458034, -0.35118096, -0.23518093, -0.28556424],
       [-0.53780919, -0.7577302 ,  0.56304952,  1.07203261, -0.24005578],
       [ 2.97461715,  0.52348617, -0.22350607, -0.62213846,  0.81965424],
       [-0.34201292, -0.36264743,  0.66697955,  0.33645294,  0.75300631],
       [-0.67643076,  0.40410617,  1.15007298,  0.2753492 ,  1.3460658 ]])

In [12]:
np.mean (arr, axis = 1) # massivning Column o'rta arifmetigi

array([-0.30385092,  0.01989739,  0.69442261,  0.21035569,  0.49983268])

In [13]:
np.mean(arr, axis = 0)  # massivning Row o'rta arifmetigi

array([ 0.18712323, -0.07147313,  0.361083  ,  0.16530307,  0.47862127])

In [14]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.cumsum(arr2)  # 0 ~ 9 gacha bo'lgan sonlarning ketma-ketlikdagi sonlar yig'indisi

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [16]:
np.cumsum(arr, axis = 1)

array([[-0.48274814, -0.64732848, -0.99850944, -1.23369037, -1.51925461],
       [-0.53780919, -1.29553939, -0.73248987,  0.33954274,  0.09948696],
       [ 2.97461715,  3.49810332,  3.27459725,  2.65245879,  3.47211303],
       [-0.34201292, -0.70466035, -0.0376808 ,  0.29877214,  1.05177845],
       [-0.67643076, -0.27232459,  0.87774839,  1.15309759,  2.49916339]])

In [17]:
np.cumsum(arr, axis = 0)

array([[-0.48274814, -0.16458034, -0.35118096, -0.23518093, -0.28556424],
       [-1.02055733, -0.92231054,  0.21186856,  0.83685168, -0.52562002],
       [ 1.95405982, -0.39882437, -0.01163751,  0.21471323,  0.29403422],
       [ 1.6120469 , -0.7614718 ,  0.65534205,  0.55116616,  1.04704054],
       [ 0.93561614, -0.35736563,  1.80541502,  0.82651536,  2.39310634]])