<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/main/mohirdev_NumPy_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [14]:
import numpy as np

In [15]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>

In [16]:
np.show_config

<function numpy.__config__.show(mode='stdout')>

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

In [18]:
arr2 = list (range (1,10,1))
arr2

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
np.array(arr2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

`💡Ishora` numpy.array

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [20]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [21]:
arr4 = np.random.randn(5,5)
arr4

array([[-0.25459513,  0.11823071, -0.1410017 , -1.3588333 , -0.85625169],
       [ 0.06600584, -0.54094252,  0.75117265, -0.25122306,  0.80134107],
       [-0.99184599,  1.21011992,  1.12437743,  0.79464156, -0.18315921],
       [-1.3597652 ,  1.88440846, -0.13971659, -1.86331742,  0.43439067],
       [-0.32989853, -0.87727237,  1.59230467, -2.01643159, -0.38131109]])

In [22]:
np.size(arr4)

25

In [23]:
arr4.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [25]:
help (np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [33]:
arr6 = np.zeros(12)
arr6

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
arr6 [5] = 1
arr6

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [36]:
arr7 = np.arange (20, 60, 1)
arr7

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [37]:
arr8 = np.arange(10)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
teskari = arr8[::-1]
teskari

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [40]:
arr9 = np.arange(12, 21, 1).reshape(3, 3)
arr9

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [41]:
arr10 = np.array ([
    3, 7, 0, 0, 9, 0
])
np.nonzero(arr10)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [43]:
arr11 = np.random.randn(2, 2, 2)
arr11

array([[[ 0.38427025, -1.28854963],
        [-0.9978215 ,  0.95085737]],

       [[-0.05037206,  0.91556257],
        [-0.31020828,  1.98419136]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [44]:
arr12 = np.random.randn(9, 9)
print (np.max (arr12))
print (np.min (arr12))

2.8747352631776795
-2.7246103556454724


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [45]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [46]:
arr14_a = np.random.randn(6, 3)
arr14_b = np.random.randn(3, 4)
print (arr14_a)
print (arr14_b)

[[ 0.4035184   0.66821777  0.81425601]
 [ 0.37968801 -0.48076842 -0.80076414]
 [-0.36249367  0.02443162  0.05374274]
 [ 0.75918019  0.1667341  -1.01006363]
 [-1.11213432 -1.84758615 -0.91490117]
 [ 0.04382212 -0.74811452 -0.29445862]]
[[ 1.00624902  2.52783293 -1.28498998 -0.53432326]
 [-0.41035689  0.87331544  0.57129685 -1.79970385]
 [ 1.14268085  0.79817635  0.90118672 -0.62941982]]


In [47]:
np.dot(arr14_a, arr14_b)

array([[ 1.06226699,  2.25351189,  0.5970303 , -1.93071222],
       [-0.33567052, -0.09922562, -1.48419478,  1.16638146],
       [-0.31337378, -0.85209073,  0.52819068,  0.11589237],
       [-0.45867653,  1.25848325, -1.7905402 , -0.06996558],
       [-1.40635441, -5.15506774, -0.45093549,  4.49520407],
       [ 0.01461768, -0.77759488, -0.74906865,  1.50830749]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [48]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [49]:
arr_a = np.array([
    1, 2
])
arr_b = np.array([
    4, 5
])
print (arr_a)
print (arr_b)

[1 2]
[4 5]


In [53]:
print(arr_a [0] > arr_b [0])
print(arr_a [1] > arr_b [1])

print(arr_a [0] >= arr_b [0])
print(arr_a [1] >= arr_b [1])

print(arr_a [0] < arr_b [0])
print(arr_a [1] < arr_b [1])

print(arr_a [0] <= arr_b [0])
print(arr_a [1] <= arr_b [1])

False
False
False
False
True
True
True
True


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [54]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-54-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-54-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-54-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [58]:
arr18_a = np.arange (1, 10, 1)
arr18_b = np.arange (1, 10, 2)
print (arr18_a)
print (arr18_b)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [59]:
np.intersect1d(arr18_a, arr18_b)

array([1, 3, 5, 7, 9])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [60]:
arr19_a = np.random.randn(6, 3)
arr19_b = np.random.randn(3, 4)
print (arr14_a)
print (arr14_b)

[[ 0.4035184   0.66821777  0.81425601]
 [ 0.37968801 -0.48076842 -0.80076414]
 [-0.36249367  0.02443162  0.05374274]
 [ 0.75918019  0.1667341  -1.01006363]
 [-1.11213432 -1.84758615 -0.91490117]
 [ 0.04382212 -0.74811452 -0.29445862]]
[[ 1.00624902  2.52783293 -1.28498998 -0.53432326]
 [-0.41035689  0.87331544  0.57129685 -1.79970385]
 [ 1.14268085  0.79817635  0.90118672 -0.62941982]]


In [62]:
butun = np.floor(arr19_a)
butun

array([[ 0.,  2., -1.],
       [ 1., -1.,  0.],
       [-1.,  0.,  0.],
       [ 0.,  1., -1.],
       [-1., -2.,  0.],
       [-1.,  0.,  0.]])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [66]:
arr20 = np.random.rand(3, 3)
arr20

array([[0.31531904, 0.9281322 , 0.39768582],
       [0.1599117 , 0.55637215, 0.16631314],
       [0.29355173, 0.54461996, 0.73449533]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [69]:
arr21 = np.random.randn(10)
arr21

array([-1.12508302, -0.08659044, -0.49995148,  1.14763981,  1.20135742,
       -0.28973167,  0.39470944,  1.71264345,  1.35730395, -0.86717238])

In [70]:
np.sort (arr21)

array([-1.12508302, -0.86717238, -0.49995148, -0.28973167, -0.08659044,
        0.39470944,  1.14763981,  1.20135742,  1.35730395,  1.71264345])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [72]:
arr22_a = np.random.randn(10)
arr22_b = np.random.randn(10)
print (arr22_a)
print (arr22_b)
np.allclose(arr22_a, arr22_b)

[ 0.48369219 -1.25896261  0.5652187   0.52698194 -1.98634407  0.30838035
 -2.27564162  0.29078516 -0.69850303  0.64305193]
[-0.29156141  0.4850502  -0.59498089 -1.90263633 -0.42467535  1.50090634
  1.15414229  0.26243358 -0.4623766  -0.0604059 ]


False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [74]:
arr23_a = np.random.randn(6, 3)
arr23_b = np.random.randn(3, 4)
print (arr23_a)
print (arr23_b)
np.dot (arr23_a, arr23_b)

[[-1.48468762 -0.92662177  0.52663983]
 [-0.96241452 -0.07790099  0.39587841]
 [ 1.05903309 -1.59366948  1.56174308]
 [ 1.0335731   0.35961309 -0.83160338]
 [-2.16762923 -1.17006967  0.34536196]
 [-1.13257533  0.72188321 -0.2943815 ]]
[[-1.27790565  0.30026373 -2.47814917 -0.25090774]
 [-0.40577411 -2.50589467  0.09298556  0.8402472 ]
 [ 0.07707392 -0.65780802  0.23966199 -0.9525778 ]]


array([[ 2.31388002,  1.5297908 ,  3.71933051, -0.90773715],
       [ 1.29199706, -0.3541785 ,  2.4726401 , -0.20108382],
       [-0.5863049 ,  3.28422996, -2.39833977, -3.0924777 ],
       [-1.53082552, -0.04377264, -2.72721322,  0.83499932],
       [ 3.27142802,  2.05402903,  5.34567913, -0.76825695],
       [ 1.13171376, -1.95538807,  2.80326327,  1.17115354]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [79]:
arr24 = np.random.randn(5)
print (arr24)
amax = np.max (arr24)
print (amax)
arr24[2] = 0
arr24

[ 0.04156356  0.65449249  0.65557848  0.4065527  -0.27096247]
0.6555784780753351


array([ 0.04156356,  0.65449249,  0.        ,  0.4065527 , -0.27096247])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [80]:
# Bugungi sana
today = np.datetime64('today', 'D')

# Kecha
yesterday = today - np.timedelta64(1, 'D')

# Ertaga
tomorrow = today + np.timedelta64(1, 'D')

print("Kecha:", yesterday)
print("Bugun:", today)
print("Ertaga:", tomorrow)

Kecha: 2024-10-29
Bugun: 2024-10-30
Ertaga: 2024-10-31


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [81]:
# 2016 yil yanvar oyidagi barcha sanalarni aniqlaymiz
january_2016 = np.arange('2016-01-01', '2016-02-01', dtype='datetime64[D]')

print(january_2016)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [89]:
random_array = np.random.rand(10) * 10  # 0 dan 10 gacha bo'lgan musbat sonlar

# Butun qismini ajratib olish
integer_part = np.floor(random_array).astype(int)

print("Tasodifiy massiv:", random_array)
print("Butun son qismi:", integer_part)

Tasodifiy massiv: [6.30532455 6.85367599 4.32165271 9.88892142 2.55091559 2.631201
 5.80466981 2.85280474 9.48197433 2.16786573]
Butun son qismi: [6 6 4 9 2 2 5 2 9 2]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [92]:
arr28 = np.random.rand(10) * 10
print (arr28)
np.sum (arr28)

[8.72295365 4.16836558 0.99529267 7.07675761 5.87515264 2.69012274
 3.75880966 1.22290708 5.65007147 1.7816746 ]


41.94210770778631

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [93]:
vector = np.array([1, 2, 3, 4, 5])

# Har bir qiymatdan keyin 3 ta nol qo'shish
expanded_vector = np.zeros(len(vector) * 4 - 3, dtype=int)  # Natijaviy vektor uzunligini hisoblash
expanded_vector[::4] = vector  # Har 4-elementga asl vektor qiymatlarini yozish

print(expanded_vector)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [94]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Slayding oynada to'rtlik qismni ajratish
b = np.array([a[i:i+4] for i in range(len(a) - 3)])

print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [98]:
arr31 = np.random.rand(10) * 10
print(arr31)
np.argmax(arr31)

[4.01075571 1.49875469 6.49327513 6.30420438 8.83601666 1.19189525
 5.4501571  5.24434128 4.92450763 2.30898952]


4

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [ ]:
savol = input("Data Science mutaxassisi uchun Senior darajaga necha yilda chiqish mumkin?\n")
print(savol)