<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/main/NumPy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
data1 = [23, 15, 12, -0.26, 14.226, -95] # list
arr1 = np.array (data1) # array (massivli jadval)
print (arr1)
arr1

[ 23.     15.     12.     -0.26   14.226 -95.   ]


array([ 23.   ,  15.   ,  12.   ,  -0.26 ,  14.226, -95.   ])

In [ ]:
data2 = (25, 62, 36, -95, -0.36, -15.2) # tupple
arr2 = np.array(data2) # array (massivli jadval)
arr2

array([ 25.  ,  62.  ,  36.  , -95.  ,  -0.36, -15.2 ])

In [ ]:
arr1.ndim  # massiv o'lchami

1

In [ ]:
arr2.ndim

1

In [ ]:
data3 = [[1, 2, 3], [4, 5, 6]] # list ichidagi ma'lumot
arr3 = np.array(data3)
print(arr3)
arr3.ndim

[[1 2 3]
 [4 5 6]]


2

In [ ]:
data4 = [[1, 2, 3], [4, 5, 6],[7, 8, 9]] # list
arr4 = np.array(data4) # array
print (arr4)
arr4.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [ ]:
arr3.shape # qator va ustunlar (raw and column) r/c


(2, 3)

In [ ]:
arr4.shape

(3, 3)

In [ ]:
arr3.size # massiv ichidagi elementlar sonini aniqlaydi

6

In [ ]:
arr4.size

9

In [4]:
arr5 = np.zeros((6, 8))  # 6 ta qator va 8 ta ustundan iborat faqat elementlari 0 dan iborat massiv yaratildi
print (arr5)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
arr6 = np.ones ((2, 6)) # 2 ta qator va 6 ta ustundan iborat faqat elementlari 1 dan iborat massiv yaratildi

In [6]:
print (arr6)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [7]:
arr7 = np.arange (2, 16, 3) # 2 dan 16 gacha sonlardan 3 ta tashab sonlar chiqarib beradi
print (arr7)

[ 2  5  8 11 14]


In [8]:
arr8 = np.arange (26) # 0 dan 26 gacha sonlardan 1 ta tashab sonlar chiqarib beradi
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])