<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/main/Tartiblash(Sorting).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5)
arr

array([0.5299259 , 0.98762131, 0.51924467, 0.98897153, 0.6102852 ])

In [5]:
sorted_arr = np.sort(arr)  # 5 ta tahminiy sonlar tartiblandi
print (sorted_arr)

[0.51924467 0.5299259  0.6102852  0.98762131 0.98897153]


In [6]:
sorted_arr_teskari = -np.sort(-arr)  # 5 ta tahminiy sonlar teskari tartiblandi
print(sorted_arr_teskari)

[0.98897153 0.98762131 0.6102852  0.5299259  0.51924467]


In [12]:
arr1 = np.random.randn (3, 5)
arr1

array([[-0.28415463, -1.01087319,  1.77631344, -1.04819232,  0.43398212],
       [ 0.32392675, -1.17535259,  0.31567819,  0.54128104,  0.08881789],
       [-1.01629757, -0.94722827,  0.96756587, -1.03556167,  0.36965299]])

In [15]:
sorted_arr1 = np.sort(arr1, axis = 0)  # massiv Column bo'yicha tahlandi
print(sorted_arr1)

[[-1.01629757 -1.17535259  0.31567819 -1.04819232  0.08881789]
 [-0.28415463 -1.01087319  0.96756587 -1.03556167  0.36965299]
 [ 0.32392675 -0.94722827  1.77631344  0.54128104  0.43398212]]


In [17]:
sorted_arr1 = np.sort(arr1, axis = 1) # massiv Row bo'yicha tahlandi
print(sorted_arr1)

[[-1.04819232 -1.01087319 -0.28415463  0.43398212  1.77631344]
 [-1.17535259  0.08881789  0.31567819  0.32392675  0.54128104]
 [-1.03556167 -1.01629757 -0.94722827  0.36965299  0.96756587]]
