<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/main/Universal_funksiyalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Unary (funksiya ichiga faqat bitta argument qo'sha olamiz)
sqrt, square, exp, log, modf, sign, isnan funksiyalarini ko'rib chiqamiz.

In [2]:
arr = np.arange (10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt (arr)  # massive ichidagi elementlarning kvadrat ildizini hisoblaydi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.square (arr) # massive ichidagi elementlarning kvadratni hisoblaydi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
np.exp (arr) # massive ichidagi elementlarning rxponent qiymati ya'ni e=2.71 va 2 ning 2.71 darajasini hisoblaydi.

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [7]:
np.log (arr) # massiv ichidagi elementlarning logarifmini hisoblaydi

<ipython-input-7-31a630e93d3e>:1: RuntimeWarning: divide by zero encountered in log
  np.log (arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [8]:
arr1 = np.random.randn (6, 4)
arr1

array([[ 0.66701274, -0.13597678, -1.49425122,  1.15202989],
       [-0.30917072, -0.10819067, -0.0331601 ,  2.10434516],
       [ 1.02856427, -2.42260189, -1.16293679,  1.0291771 ],
       [ 0.46556407,  0.75121497, -0.09912624, -0.87729491],
       [ 1.47818799,  0.88323801, -0.70705164, -1.7256217 ],
       [-0.61481628, -1.12849993,  0.23826811,  0.06042928]])

In [9]:
qoldiq, butun = np.modf(arr1)   # modf funksiyasi orqali qoldiq va butun qismlarga ajratib chiqaradi.
print(qoldiq)
print(butun)

[[ 0.66701274 -0.13597678 -0.49425122  0.15202989]
 [-0.30917072 -0.10819067 -0.0331601   0.10434516]
 [ 0.02856427 -0.42260189 -0.16293679  0.0291771 ]
 [ 0.46556407  0.75121497 -0.09912624 -0.87729491]
 [ 0.47818799  0.88323801 -0.70705164 -0.7256217 ]
 [-0.61481628 -0.12849993  0.23826811  0.06042928]]
[[ 0. -0. -1.  1.]
 [-0. -0. -0.  2.]
 [ 1. -2. -1.  1.]
 [ 0.  0. -0. -0.]
 [ 1.  0. -0. -1.]
 [-0. -1.  0.  0.]]


In [11]:
np.sign(arr1)  #sign funkisyasi massiv elementlarini qiymati manfiy bo'lsa -1 va aksincha musbat bo'lsa 1 ni qaytaradi

array([[ 1., -1., -1.,  1.],
       [-1., -1., -1.,  1.],
       [ 1., -1., -1.,  1.],
       [ 1.,  1., -1., -1.],
       [ 1.,  1., -1., -1.],
       [-1., -1.,  1.,  1.]])

In [13]:
np.isnan (arr1)  # bu orqali NaN (Non a Number) bo'lsa True, bo'lmasa False chiqaradi

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [15]:
arr1 [2:] = np.nan
arr1

array([[ 0.66701274, -0.13597678, -1.49425122,  1.15202989],
       [-0.30917072, -0.10819067, -0.0331601 ,  2.10434516],
       [        nan,         nan,         nan,         nan],
       [        nan,         nan,         nan,         nan],
       [        nan,         nan,         nan,         nan],
       [        nan,         nan,         nan,         nan]])

In [16]:
np.isnan (arr1)

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Binary funksiyalar (ikkita argument qabul qiluvchi funkisya)

add, multiply, maximum funksiyalarini ko'rib chiqamiz

In [18]:
arr2 = np.random.randn (5)
arr2

array([ 0.04834379, -1.67941139, -1.76752857,  0.61519682, -1.00367206])

In [19]:
arr3 = np.random.randn (5)
arr3

array([ 0.1361197 ,  0.05351924, -0.21866952, -0.8742402 ,  1.0792024 ])

In [20]:
np.add(arr2, arr3)   # ikkita massivni qo'shadi mos elementlarini

array([ 0.18446349, -1.62589215, -1.98619808, -0.25904339,  0.07553034])

In [21]:
np.multiply(arr2, arr3)  # ikkita massivni ko'paytiradi mos elementlarini

array([ 0.00658054, -0.08988082,  0.38650462, -0.53782979, -1.08316529])

In [22]:
np.maximum (arr2, arr3)  # ikkita massivni taqqoslab, katta qiymatlarini chiqaradi

array([ 0.1361197 ,  0.05351924, -0.21866952,  0.61519682,  1.0792024 ])

In [23]:
np.minimum (arr2, arr3)  # ikkita massivni taqqoslab, kichik qiymatlarini chiqaradi

array([ 0.04834379, -1.67941139, -1.76752857, -0.8742402 , -1.00367206])